### ISSUE TITLE
Add e2e testing

### ISSUE THREAD

**Issue by tlei123** [Tze1/react-expensify#3]
Implement e2e testing.

Use nightwatch.  Start with Chromedriver for now, then expand testing later to other browsers.

### Subtasks
- [x] Create Login helper
- [x] Create Expense-data test-fixture(s)
- [x] Create Delete-expenses test-case
- [x] Create Add-expenses test-case
- [x] Create Filter-expenses test-case
- [x] Create Sort-expenses test-case
- [x] Create Edit-expense test-case
- [ ] Open follow-up Issues for other webdriver-setups beyond Chrome.

**Comment by tlei123** [comment]
Coding done and merged.

Documentation will be done in tze1.github.io \[[\#2](https://github.com/Tze1/tze1.github.io/issues/2)].

New tickets opened for adding Firefox (#17), Safari (#18), and Internet Explorer (#19).

Closing ticket.
